language: csharp
sudo: required
mono: none
dotnet: 5.0.202
branches:
  only:
    - master
addons:
  apt:
    packages:
    - sshpass
before_script:
  - chmod -R a+x scripts

script:
  - cd src/ApiaryDiary.Api
  - dotnet restore
  - dotnet build
  - cd ..
  - cd ..
  - ls
after_success:
  - echo Executing after success scripts on branch $TRAVIS_BRANCH
  - ./scripts/docker-publish.sh
  - sshpass -p $haslo  ssh root@$IP 'docker-compose up'
notifications:
  email:
    on_success: never
    on_failure: always
