language: csharp
sudo: required
mono: none
dotnet: 5.0.202
branches:
  only:
    - master
before_install:
  - sudo apt-get -q update
addons:
  apt:
    packages:
    - sshpass
before_script:
  - chmod -R a+x scripts

script:
  - ls
  - ./scripts/travis-build.sh
  - ls
  - ./scripts/travis-success.sh
after_success:
  - ls
  - echo Deploy to server $IP on branch $TRAVIS_BRANCH
  - ./scripts/travis-success.deploy.sh
  email:
    on_success: never
    on_failure: always
