language: csharp
sudo: required
mono: none
dotnet: 5.0.202
branches:
  only:
    - master
before_script:
  - chmod -R a+x scripts
script:
  - dotnet --info
after_success:
  - echo Executing after success scripts on branch $TRAVIS_BRANCH
  - sudo apt-get install sshpass
  - echo $ApiaryDiaryIPPassword
  - echo $pa
  - echo "$pa"
  - echo "$IP"
  - echo $IP
  - ls
  - ./scripts/docker-publish.sh
  - sshpass -p "$pa" ssh root@46.101.251.246 'docker-compose up' 
  - sshpass -p $pa ssh root@46.101.251.246 'docker-compose up' 
 - cd ..
  - ls
notifications:
  email:
    on_success: never
    on_failure: always
