language: csharp
sudo: required
mono: none
dotnet: 5.0.202
branches:
  only:
    - master
before_script:
  - chmod -R a+x scripts
script:
  - cd src/ApiaryDiary.Api
  - dotnet restore
  - dotnet build
after_success:
  - echo Executing after success scripts on branch $TRAVIS_BRANCH
  - sudo apt-get install sshpass
  - echo $testVariable
  - echo '$testVariable'
  - echo root@$testVariable
  - echo 'root@$testVariable'
  - echo $ApiaryDiaryIPPassword
  - echo $ApiaryDiaryIPPassword
  - sshpass -p $pass ssh root@$IP 'docker-compose up'
  - sshpass -p $ApiaryDiaryIPPassword ssh root@46.101.251.246 'docker-compose up'
  - cd /etc/nginx/sites-available
  - ls
notifications:
  email:
    on_success: never
    on_failure: always
