language: csharp
sudo: required
mono: none
dotnet: 5.0.202
branches:
  only:
    - master
before_script:
  - chmod -R a+x scripts
script:
  - cd src/ApiaryDiary.Api
  - dotnet restore
  - dotnet build
after_success:
  - echo Executing after success scripts on branch $TRAVIS_BRANCH
  - echo Executing after success scripts on branch $TRAVIS_BRANCH
  - echo Publishing application
  - echo Loging to server...
  - sshpass -p $ApiaryDiaryIPPassword ssh -o StrictHostKeyChecking=no root@$ApiaryDiaryIP
  - echo Logged to server
  - ls
  -  nano docker-compose.yml
notifications:
  email:
    on_success: never
    on_failure: always