language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 5.0.100
branches:
  only:
    - master
before_script:
  - chmod -R a+x scripts
script:
  - dotnet restore
  - dotnet build
after_success:
  - echo Executing after success scripts on branch $TRAVIS_BRANCH
  - echo The end !!!!
notifications:
  email:
    on_success: never
    on_failure: always