language: csharp
services:
  - docker
sudo: required
mono: none
dotnet: 6.0
branches:
  only:
    - master
before_install:
- sudo apt-get -q update
- sudo apt-get install sshpass
addons:
apt:
packages:
- sshpass
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/travis-build.sh
  - ./scripts/travis-success.sh

after_success:
  - echo Deploy to server $IP on branch $TRAVIS_BRANCH
  - ./scripts/travis-deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always