version: '3.7'
services: 
    api:
        image: buckfast/apiarydiary-api
        ports: 
          - "5000:5000"
    ui:
        image: buckfast/apiarydiary-ui
        ports: 
          - "4200:80"
        depends_on: 
          - api