version: '3.7'
services:
    postgres:
        image: postgres
        ports:
          - "5432:5432"
        container_name: postgres_development
        restart: unless-stopped
        shm_size: '4gb'
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD:
          POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
          - postgres:/var/lib/postgresql/data

volumes: 
  postgres:
    driver: local