@url = http://localhost:5000
//@usersApi = {{url}}/Users
@usersApi = {{url}}/Users
###
GET http://localhost:5000/test 

###
###
GET http://localhost:5000/Users/Account/location
###
@email = admin@apiary.com
@password = password
@role = admin
@accessToken = secret

### Sign-up as the administrator
POST {{usersApi}}/Account/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "role": "{{role}}",
  "claims": {
    "permissions": ["all"]
  }
}

### Login as the administrator
# @name sign_in_admin
POST {{usersApi}}/Account/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
@accessToken= {{sign_in_admin.response.body.$.accessToken}}
@refreshToken = {{sign_in_admin.response.body.$.refreshToken}}

###
# @name refresh_tokens
POST {{usersApi}}/Account/refresh-tokens
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###
@accessToken= {{refresh_tokens.response.body.$.accessToken}}
###
GET {{url}}/account
Authorization: Bearer {{accessToken}}


### Travis debbuging
POST https://api.travis-ci.com/job/<JOB_ID>/debug
Authorization: token {{accessToken}}
Content-Type: application/json
Travis-API-Version: 3
Accept: application/json
{
  "quiet": true
}

